### PR TITLE
Expose timestamp to JSON formatter so it gets included in File Reporter

### PR DESCRIPTION
**Pull request by larsnaesbye**
Fixes https://github.com/gravitee-io/issues/issues/5097

### CODE REVIEW

**Comment by larsnaesbye** [comment]
@aelamrani I think this could get merged easily. It was suggested by David on Slack, and we are using it ourselves. It fixes the issue of JSON formatter not writing timestamps because of missing getTimestamp function.

**Comment by phiz71** [comment]
LGTM.
Could you rebase on master and squash your commit please ?

**Comment by larsnaesbye** [comment]
Squashed and force-pushed :)

**Comment by phiz71** [comment]
thx 👍🏻

**Pull request merged**
